f
node-modules/common-bin pull request #6
Opened 2017-03-13 13:16 UTC by popomore

2017-03-13 13:19 UTC, popomore commented
先提交下看看

yargs 有一些限制

1. 主命令不支持 positional argument https://github.com/yargs/yargs/issues/570
1. 会自动处理 help version 参数，这样到不了子命令 https://github.com/yargs/yargs/blob/master/yargs.js#L1037

2017-03-13 13:32 UTC, atian25 commented
- 第一点可以用 `demondArgument` 还是啥了，有个属性，不过不能转换为属性名
- 第二点需要关掉 `help()` 自己处理，或者是 `help(options)` 不知道能否处理

2017-03-13 14:58 UTC, popomore commented
改成提前 parse，不过 help

2017-03-14 00:11 UTC, fengmk2 commented
readme 也得相应改一下

2017-03-14 00:11 UTC, fengmk2 approved these changes

2017-03-14 08:16 UTC, popomore commented
@atian25 除了 positional argument 外其他看看，再考虑先合并 #5 还是直接合到 master。

2017-03-14 08:37 UTC, atian25 reviewed
OK，我取下来本地看看。

2017-03-14 08:37 UTC, atian25 commented on .idea/common-bin.iml
> +<?xml version="1.0" encoding="utf-8"?>
这几个文件加到 ignore

2017-03-14 08:52 UTC, popomore commented on .idea/common-bin.iml
> +<?xml version="1.0" encoding="utf-8"?>
.idea 是不是要删除

2017-03-14 08:53 UTC, popomore commented
本来想把 usage 的值取出来用作 default command 参数，发现他在闭包里。

2017-03-14 08:59 UTC, popomore commented
等你 review 完一起改

2017-03-14 09:06 UTC, atian25 requested changes
其他 +1。

要不要支持下 `this.options = {}` 等的处理，这种写法感觉更简洁一点。

2017-03-14 09:06 UTC, atian25 commented on lib/command.js
> +    this.origin = argv || process.argv.slice(2);
origin 这个命名怪怪的

2017-03-14 09:06 UTC, atian25 commented on lib/command.js
>      this.commandMapping = new Map();
`<commandName, Command>`

2017-03-14 09:06 UTC, atian25 commented on lib/command.js
> +   * @param {String} fullPath - the command directory, args will be join by `path.join`
`args will be join by path.join` 干掉

2017-03-14 09:06 UTC, atian25 commented on lib/command.js
>      assert(fs.statSync(fullPath).isDirectory(), `${fullPath} is not a directory, maybe you should use addCommand.`);
`addCommand` -> `add`

2017-03-14 09:06 UTC, atian25 commented on lib/command.js
> +    debug('[%s] loaded command `%s` from directory `%s`', this.constructor.name, names, fullPath);
第二个应该是 `%j`

2017-03-14 09:06 UTC, atian25 commented on lib/command.js
> +   * @param {String} name -
missing jsdoc

2017-03-14 09:06 UTC, atian25 commented on lib/command.js
> +    assert(this.commandMapping.has(name), `${name} should be registered`);
- `had been`
- 另外需要检查 name 存在么?

2017-03-14 09:06 UTC, atian25 commented on lib/command.js
> +      rawArgv.splice(rawArgv.indexOf(commandName), 1);
只删除当前? 这时候 commandName 肯定是 `argv._[0]` 了吧?

2017-03-14 09:06 UTC, atian25 commented on lib/command.js
> +      yield this.helper.callFn(command[DISPATCH], [], command); return;
`return` 换行

2017-03-14 09:06 UTC, atian25 commented on lib/command.js
> +      argv: this.yargs.argv,
不直接用上面的 parse 结果?

2017-03-14 09:06 UTC, atian25 commented on test/fixtures/my-bin/command/start.js
>      this.aliases = [ 'begin' ];
这句要改吧?

2017-03-14 09:06 UTC, atian25 commented on test/fixtures/my-git/command/remote/add.js
> +    this.yargs.options({
相比起来，我还是更喜欢赋值的写法。

2017-03-14 09:07 UTC, atian25 commented on .idea/common-bin.iml
> +<?xml version="1.0" encoding="utf-8"?>
嗯，删除掉，再加到 gitignore

2017-03-14 09:09 UTC, atian25 commented
- 要不要支持下 `this.options = {}` 等的处理，这种写法感觉更简洁一点。
- 不支持 `position arguments` 的，不过也还好吧，自己处理
- 中午聊的 `bash completion` 试试能不能支持

2017-03-14 09:49 UTC, popomore commented on lib/command.js
> +    this.origin = argv || process.argv.slice(2);
originArgs?

2017-03-14 09:52 UTC, atian25 commented on lib/command.js
> +    this.origin = argv || process.argv.slice(2);
originArgv 吧，不过这个命名跟下面的 rawArgv 的有点冲突了，前者是被处理过的，后者才是原始的吧？

2017-03-14 09:52 UTC, popomore commented on lib/command.js
> +    debug('[%s] loaded command `%s` from directory `%s`', this.constructor.name, names, fullPath);
数组 toString 就是以 , 分割

2017-03-14 09:52 UTC, atian25 commented on lib/command.js
> +    this.origin = argv || process.argv.slice(2);
不过 rawArgv 应该也传处理过的才对吧？ 直接合并这 2 个？

2017-03-14 09:53 UTC, popomore commented on lib/command.js
> +    assert(this.commandMapping.has(name), `${name} should be registered`);
这里就是检查 name 是否存在，不存在报错

2017-03-14 09:59 UTC, popomore commented on lib/command.js
> +      rawArgv.splice(rawArgv.indexOf(commandName), 1);
比如某些参数写在了前面，现在没有过滤前面的参数（好像没有特定规则）

2017-03-14 10:00 UTC, popomore commented on lib/command.js
> +      argv: this.yargs.argv,
恩，argv 会自己处理 help 和 version

2017-03-14 10:03 UTC, atian25 commented on lib/command.js
> +      rawArgv.splice(rawArgv.indexOf(commandName), 1);
`--baseDir=abc  add ` 这种场景？ 应该不支持的吧？

2017-03-14 10:04 UTC, atian25 commented on lib/command.js
> +      argv: this.yargs.argv,
关掉 help 和 version, 到下面再注册上去?

2017-03-14 10:12 UTC, popomore commented on test/fixtures/my-bin/command/start.js
>      this.aliases = [ 'begin' ];
好像没这个测试

2017-03-14 10:19 UTC, popomore commented on lib/command.js
> +    this.origin = argv || process.argv.slice(2);
就叫 rawArgv 吧

2017-03-14 10:20 UTC, popomore commented on lib/command.js
> +      argv: this.yargs.argv,
这里他自己处理就省的再写了

2017-03-14 10:21 UTC, popomore commented
改了，再看看

2017-03-14 10:45 UTC, atian25 commented on lib/command.js
>        const command = new Command(rawArgv);
这里如果有那种在前面的场景，最好加个用例

2017-03-14 10:45 UTC, atian25 commented on lib/command.js
> +  set options(opt) {
几个常用的也加下？如 `usage`？

2017-03-14 10:49 UTC, atian25 commented
其他差不多，主要是对用户侧的  API 确定就没问题了

2017-03-14 11:03 UTC, popomore commented on lib/command.js
>        const command = new Command(rawArgv);
用例之后可以慢慢加，感觉原来的用例像 example，可以把 my-git 放到 example 目录。先把功能搞定改 egg-bin

2017-03-14 11:05 UTC, popomore commented
先加上了，合到你那个 PR 的话我就不改了 commit 了，到时一起 squash

2017-03-14 11:20 UTC, atian25 commented
直接合这个关闭那个吧。合了，我明天 link 改改 egg-bin

发自我的 iPhone

> 在 2017年3月14日，19:05，Haoliang Gao <notifications@github.com> 写道：
> 
> 先加上了，合到你那个 PR 的话我就不改了 commit 了，到时一起 squash
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-03-14 12:13 UTC, popomore commented
移到 master 了

2017-03-14 12:38 UTC, merged

2017-03-14 12:39 UTC, atian25 commented
明天我 link 改改 egg-bin 再发版本

2017-03-15 00:54 UTC, atian25 commented
几个遗留问题：
- `command[DISPATCH]` 直接调用就好了，不需要 `this.helper.callFn`
- README 文档，顶部的 `Program` 描述没改，下面没有 `options=` 和 `usage=` 等的说明，并建议用这个。
- `alias` 目前的实现方式，会使 help 重复，应该用 `aliases` ，而不是注册多个 Command

```bash
Usage: my-git remote <add/remove>

Commands:
  completion  generate bash completion script
  add         Adds a remote named <name> for the repository at <url>
  remove      Remove the remote named <name>
  rm          Remove the remote named <name>
```

2017-03-15 03:00 UTC, atian25 commented
顺便记录下，可能存在的需求，后面有空做
- redirect to another command
- provide hook to change `rawArgv` pass to sub command
- bash-completion